version: "3.9"
services:
  database:
    image: "couchdb:3.1.1"
    container_name: "my-poker-couch"
    ports: 
      - 5984:5984 
    # env-file?
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes: 
      - couchdb-data:/opt/couchdb/data
    networks: 
      - backend-tier
  parser:
    image: chris060986/poker-hh-parser:local
    container_name: pokerstars-parser
    ports: 
      - 5000:5000
    networks: 
      - backend-tier
      - bridge-tier
  #front-end
  # http webserver to deliver html frontend
volumes:
  couchdb-data:
    external: true

networks: 
  backend-tier:
    name: poker-bro-backend
    labels:
      com.pokerbro.description: "basic network for all backend service"
  bridge-tier:
    name: poker-bro-bridge
    labels:
      com.pokerbro.description: "network for bridge between shipper and backend"